### ISSUE TITLE
--fix is not fixing

### ISSUE THREAD

**Issue by ctmm** [biotope/biotope-quality-gate#132]
I followed the instructions provided for IDE integration. 

However, when running `biotope-quality-gate` using the `--fix` flag, some rules are not fixed (quotes and dangling commas).

NOTE
VSCode's ESLint extension throws an error, whenever opening a new `.ts` file:
```
Error: ESLint configuration in /Users/my-user/my-project/node_modules/@biotope/quality-gate/config/logic/recommended.js is invalid:
	- Unexpected top-level property "overrides[0].extends".
```

**Comment by luke-m** [comment]
I also have this issue and I hate quality-gate because of it. Please fix.
