### ISSUE TITLE
RFC: Use prettier for fixing 

### ISSUE THREAD

**Issue by jurekbarth** [biotope/biotope-quality-gate#16]
Right now eslint:fix fixes by far not everything that i would suspect to be fixable automagically. 

Prettier (https://prettier.io/) uses a different approach by rewriting the whole code, based on the ruleset i.e. eslint rules. Therefor a lot of stuff will be fixed. We use it in biotope-build and it enhanced the code style and rules, better than eslint alone before.

**Comment by timomayer** [comment]
vote for prettier 👍 
but please keep in mind that code optimization should only run when quality gate is running on a devs local maschine BEFORE a commit.
it should not run on a jenkins server during our normal build process. there only "checks" should run, no optimizations.

**Comment by tiagomapmarques** [comment]
@timomayer We have that covered. From the docs:
![screen shot 2019-03-01 at 14 46 59](https://user-images.githubusercontent.com/704002/53645565-08c98780-3c31-11e9-9234-2c7af07ab341.png)

@jurekbarth Will investigate. Probably even fixes #17 :)

**Comment by ctmm** [comment]
@jurekbarth 

While working on #17 I considered to use prettier for code formatting instead of eslint.

I tested that option and, although it is possible, we decided not to pursue that route as it would require a complete refactor of the project.

That being said, I ask you to consider closing this issue as we do not currently have the resources to integrate prettier and the fix on #17 already adds eslint's autofixing.

Looking forward for your input!

**Comment by jurekbarth** [comment]
After a long thought about this i regret closing this issue and not being upright standing here for prettier. There's no way eslint can replace prettier. 
Prettier follows a completely different approach, which helps with everything code styling related. Imho i don't care about whatever prettier uses as formatting style, it's common all over open source to use these standards. So i would use these defaults and do not opt in for any special stuff. 
Furthermore i think there's still a place for eslint for everything code quality related, this could be part of this repo, while disabling anything formatting related and give that in the hands of a standard prettier.
What do you think about that? 
fyi @dannystey @timomayer @SheepFromHeaven

**Comment by SheepFromHeaven** [comment]
@jurekbarth I agree with having prettier as a separate tool. For me to work with quality gate, the important point is, that quality gate uses standard configs, like an .eslintrc file as config and not an own special format. This will enable the usage of eslint plugins in IDEs, which will allow me to format on save to pass the quality gates linting.
Other than that I would say it is the developers choice, if she want's to use prettier or not in their project. Quality gate should just take care of the linting.

**Comment by dannystey** [comment]
@jurekbarth @SheepFromHeaven I totally agree with you both.

**Comment by timomayer** [comment]
I agree with removing prettier and making all lint configurations read from the root directory of the project so they can be edited by the project team and found there by the IDE.

The main purpose of the quality-gate is to ensure that agreed coding standards are folowed by all developers in the project team and no code avoiding that rules can be merged into the master or even in develop.
Fixing already existing code is a seperate topic and should not be bundled in the quality gate.

So i think there are 3 things:
1. Remove prettier
2. Make all linter configurations read from the projects root folder where they can be also found by IDEs.
3. Thats an addition: if a linter config is missing in projects root quality gate should ask to either skip this linter or copy the biotope-quality-gate default config for this linter to the projects root directory

**Comment by jurekbarth** [comment]
@timomayer 
1. there's not prettier in here at the moment, i would like to have it, so that it's possible to fix issues regarding formatting. Code quality increases with this addition and DX is enhanced. Why do you not want prettier?
2. I agree we need IDE support, though it's possible without having the files in root i guess, because create react app has linting and prettier and there's just a line in the package.json
3. I would like to have it the other way around if possible. You could *eject* from the standards and then everything is installed in your project. The reason behind would be that we can update these standards and if someone updates the package version the *newer* standard is applied

**Comment by tiagomapmarques** [comment]
As discussed offline, Prettier should be added on a project-basis due to eslint and stylelint having better APIs for programatically linting code.
As for other issues discussed in this thread, separate issues should be filed.
Closing.
