### ISSUE TITLE
Fix not fixing

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-quality-gate#17]
I tried to add quality gate to my project and fix my code automagically.

Result:
Not Working.

Maybe a problem with this:
https://github.com/eslint/eslint/issues/7456

**Comment by jurekbarth** [comment]
Hey @tiagomapmarques, @ctmm  this is still an issue.

**Comment by tiagomapmarques** [comment]
As of beta-5, this is no longer an issue
