### ISSUE TITLE
discussion: move the (very complex) npm run scripts for linting to quality gate package json

### ISSUE THREAD

**Issue by timomayer** [biotope/biotope-quality-gate#224]
suggestion: we move the very complex npm run scripts for linting to the package json of the quality gate instead of having them in the boilerplate
this would result in something like
```
"scripts": {
    "lint": "qualitygate:lint",
    "lint:styles": "qualitygate:styles",
    "lint:eslint": "qualitygate:eslint",
  },
```
in boilerplate / project package.json and would make things much cleaner there. we also gain the freedom to change the lint run scripts with a qualitygate update without users have to manually update package.json in the project.

We can also add a hint in the readme, that of course every user can also use eslint etc directly in projects package json, when he wants to customize something there.

what do you think?

**Comment by RunzelRosinchen** [comment]
Would appreciate that as well, as you said: it would make the package.json much cleaner.

**Comment by timomayer** [comment]
@SheepFromHeaven whars your opinion? if you agree i would take that one and work on it.

**Comment by tiagomapmarques** [comment]
No longer relevant I think since only 2 arguments are needed - the file (or glob) and "--fix"

**Comment by SheepFromHeaven** [comment]
Agree with @tiagomapmarques
