### ISSUE TITLE
Custom indentation settings not fixable

### ISSUE THREAD

**Issue by SheepFromHeaven** [biotope/biotope-quality-gate#24]
I added a custom indentation rule: `'indent': ["error", 2],`

The eslint docs say this should be fixable. If I run it with fix, I get the error messages, but it's not fixing.

**Comment by tiagomapmarques** [comment]
@SheepFromHeaven can you confirm it's fixed?
Please take note that you may need to add `"@typescript-eslint/indent": ["error", 2],` instead of (or together with) `"indent": ["error", 2],`.

**Comment by timomayer** [comment]
@SheepFromHeaven ping
